// Pure docs generators for CLI reference, config reference, and CHANGELOG (#597).
//
// No network, git, or subprocess I/O in the pure transforms. The generate-docs.mjs
// CLI and unit tests inject filesystem / tag sources via explicit parameters.

import {
  COMMAND_DOCS,
  isDocumentedCommand,
  listDocumentedCommands,
  type CommandDoc,
} from "./command-docs.ts";
import { COMMAND_REGISTRY } from "./command-registry.ts";

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

export const GENERATED_BANNER =
  "<!-- Generated by `node scripts/generate-docs.mjs` — do not edit by hand. -->";

export const SKILL_CLI_BEGIN = "<!-- BEGIN GENERATED: cli-command-table -->";
export const SKILL_CLI_END = "<!-- END GENERATED: cli-command-table -->";

export function normalizeNewlines(text: string): string {
  return text.replace(/\r\n/g, "\n").replace(/\s+$/u, "") + "\n";
}

// ---------------------------------------------------------------------------
// CLI reference
// ---------------------------------------------------------------------------

export interface CliDocInventoryEntry {
  keyword: string;
  summary: string;
  usage: string;
  section?: string;
}

/**
 * Build the documented CLI inventory from a registry + docs map.
 * Never invents commands absent from the registry.
 */
export function buildCliInventory(
  registry: Record<string, unknown> = COMMAND_REGISTRY,
  docs: Record<string, CommandDoc> = COMMAND_DOCS,
): CliDocInventoryEntry[] {
  const keys = Object.keys(registry).filter((k) => {
    const doc = docs[k];
    if (!doc) return false;
    if (doc.documented === false) return false;
    return true;
  });
  // Preserve listDocumentedCommands order when using live sources.
  const ordered =
    registry === COMMAND_REGISTRY && docs === COMMAND_DOCS
      ? listDocumentedCommands()
      : keys.sort();
  return ordered.map((keyword) => {
    const doc = docs[keyword]!;
    return {
      keyword,
      summary: doc.summary,
      usage: doc.usage,
      section: doc.section,
    };
  });
}

/** Render host-token-agnostic usage lines with a host prefix. */
export function formatUsageLines(usage: string, hostToken: string): string[] {
  return usage
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      // Already-prefixed (shouldn't happen) or bare body.
      if (line.startsWith("/pipeline") || line.startsWith("$pipeline") || line.startsWith("pipeline ")) {
        return line.replace(/^(?:\/|\$)?pipeline/, hostToken);
      }
      // Namespaced form: "status <N>" → "/pipeline:status <N>" when first token is the keyword
      // Advance forms start with "N" or flags after N.
      if (/^N(\s|$)/.test(line) || line.startsWith("--")) {
        return `${hostToken} ${line}`;
      }
      // Subcommands: "status <N>", "config sync", "evals plan …", "loop --audit"
      const colonStyle = /^(status|unblock|override|summary|doctor|init|cleanup|intake|triage|sweep|roadmap|merge|release|logs|loop)\b/.test(
        line,
      );
      if (colonStyle) {
        // Prefer host:command for the primary synopsis line when it looks like a top-level verb.
        const m = line.match(/^(\S+)(\s+.*)?$/);
        if (m && !m[1]!.includes(" ")) {
          return `${hostToken}:${m[1]}${m[2] ?? ""}`;
        }
      }
      return `${hostToken} ${line}`;
    });
}

export function renderCliReferenceMarkdown(
  inventory: CliDocInventoryEntry[] = buildCliInventory(),
): string {
  const lines: string[] = [
    "# CLI reference",
    "",
    GENERATED_BANNER,
    "",
    "Generated from `COMMAND_REGISTRY` + `COMMAND_DOCS` (see `core/scripts/command-registry.ts`",
    "and `core/scripts/command-docs.ts`). Host skill command tables are fed from the same inventory.",
    "",
    "Invoke via the host skill (`/pipeline` in Claude Code, `$pipeline` in Codex) or the",
    "`pipeline` CLI launcher after install. Usage lines below use the neutral `pipeline` token;",
    "substitute your host form as needed.",
    "",
    "| Command | Summary |",
    "| --- | --- |",
  ];

  for (const entry of inventory) {
    const firstUsage = entry.usage.split("\n")[0]!.trim();
    const cmdCell = firstUsage.startsWith("N")
      ? `\`pipeline ${firstUsage}\``
      : `\`pipeline ${firstUsage}\``;
    // Escape pipes in summary.
    const summary = entry.summary.replace(/\|/g, "\\|");
    lines.push(`| ${cmdCell} | ${summary} |`);
  }

  lines.push("", "## Commands", "");

  for (const entry of inventory) {
    lines.push(`### \`${entry.keyword}\``, "");
    lines.push(entry.summary, "");
    lines.push("```text");
    for (const u of formatUsageLines(entry.usage, "pipeline")) {
      lines.push(u);
    }
    lines.push("```", "");
  }

  lines.push(
    "## Notes",
    "",
    "- Legacy alias `run` (equivalent to advance without detach) is dispatch-only and omitted here.",
    "- Agent-only `papercut` is hidden from operator docs; see OpenSpec / improve auto-file paths.",
    "- There is no `auto_merge` config key and the advance loop never merges; use `pipeline merge <pr>` only as a human action after `pipeline:ready-to-deploy`.",
    "",
  );

  return normalizeNewlines(lines.join("\n"));
}

/**
 * Render the fenced command-table region body for a host SKILL.md
 * (content between markers, not including the markers themselves).
 */
export function renderSkillCommandTable(
  hostToken: "/pipeline" | "$pipeline",
  inventory: CliDocInventoryEntry[] = buildCliInventory(),
): string {
  const lines: string[] = ["```"];
  for (const entry of inventory) {
    for (const u of formatUsageLines(entry.usage, hostToken)) {
      // Pad roughly like the hand-authored tables (command left, summary right).
      const pad = Math.max(2, 42 - u.length);
      lines.push(`${u}${" ".repeat(pad)}${entry.summary}`);
    }
    // Blank line between command groups for scanability.
    lines.push("");
  }
  // Drop trailing blank inside the fence.
  while (lines.length > 1 && lines[lines.length - 1] === "") lines.pop();
  lines.push("```");
  return lines.join("\n");
}

/**
 * Replace the generated region in a SKILL.md body. Returns null if markers are missing.
 */
export function replaceSkillGeneratedRegion(
  skillBody: string,
  generatedInner: string,
): string | null {
  const begin = skillBody.indexOf(SKILL_CLI_BEGIN);
  const end = skillBody.indexOf(SKILL_CLI_END);
  if (begin < 0 || end < 0 || end < begin) return null;
  const before = skillBody.slice(0, begin + SKILL_CLI_BEGIN.length);
  const after = skillBody.slice(end);
  // Ensure single newlines around the region body.
  const body = generatedInner.replace(/^\n+|\n+$/g, "");
  return `${before}\n${body}\n${after}`;
}

// ---------------------------------------------------------------------------
// Config reference
// ---------------------------------------------------------------------------

/** Minimal JSON Schema node shape we walk for docs. */
export interface JsonSchemaNode {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  properties?: Record<string, JsonSchemaNode>;
  items?: JsonSchemaNode | JsonSchemaNode[];
  anyOf?: JsonSchemaNode[];
  oneOf?: JsonSchemaNode[];
  $ref?: string;
  additionalProperties?: boolean | JsonSchemaNode;
  [key: string]: unknown;
}

function unwrapSchema(node: JsonSchemaNode | undefined): JsonSchemaNode | undefined {
  if (!node) return undefined;
  // zod-to-json-schema often wraps optionals as anyOf: [T, {type:null}] or similar.
  if (Array.isArray(node.anyOf)) {
    const nonNull = node.anyOf.find((n) => n && n.type !== "null" && (n as { const?: unknown }).const === undefined);
    if (nonNull) return { ...nonNull, description: node.description ?? nonNull.description };
  }
  if (Array.isArray(node.oneOf)) {
    const nonNull = node.oneOf.find((n) => n && n.type !== "null");
    if (nonNull) return { ...nonNull, description: node.description ?? nonNull.description };
  }
  return node;
}

function typeLabel(node: JsonSchemaNode | undefined): string {
  if (!node) return "unknown";
  const n = unwrapSchema(node) ?? node;
  if (Array.isArray(n.enum) && n.enum.length > 0) {
    return `enum: ${n.enum.map((v) => JSON.stringify(v)).join(" | ")}`;
  }
  if (n.type === "array" || (Array.isArray(n.type) && n.type.includes("array"))) {
    const items = Array.isArray(n.items) ? n.items[0] : n.items;
    const inner = typeLabel(items as JsonSchemaNode | undefined);
    return `array of ${inner}`;
  }
  if (n.type === "object" || n.properties) return "object";
  if (Array.isArray(n.type)) return n.type.filter((t) => t !== "null").join(" | ") || "unknown";
  if (typeof n.type === "string") return n.type;
  if (n.properties) return "object";
  return "unknown";
}

function renderConfigField(
  name: string,
  node: JsonSchemaNode,
  depth: number,
): string[] {
  const n = unwrapSchema(node) ?? node;
  const heading = "#".repeat(Math.min(depth, 6));
  const lines: string[] = [];
  lines.push(`${heading} \`${name}\``);
  lines.push("");
  const desc = (n.description ?? node.description ?? "").trim();
  if (desc) lines.push(desc, "");
  lines.push(`- **Type:** \`${typeLabel(node)}\``);
  if (Array.isArray(n.enum) && n.enum.length > 0) {
    lines.push(`- **Allowed values:** ${n.enum.map((v) => `\`${JSON.stringify(v)}\``).join(", ")}`);
  }
  lines.push("");

  const props = n.properties;
  if (props && typeof props === "object") {
    for (const [child, childNode] of Object.entries(props)) {
      lines.push(...renderConfigField(`${name}.${child}`, childNode, depth + 1));
    }
  }
  return lines;
}

/**
 * Render docs/config.md from a JSON Schema object (typically generateConfigSchema()).
 * Explicitly never documents `auto_merge` even if somehow present.
 */
export function renderConfigReferenceMarkdown(schema: JsonSchemaNode): string {
  const props = schema.properties ?? {};
  const lines: string[] = [
    "# Config reference",
    "",
    GENERATED_BANNER,
    "",
    "Generated from `PartialConfigSchema` in `core/scripts/config.ts` via `generateConfigSchema()`.",
    "Commit a `.github/pipeline.yml` to override defaults. Keys are optional unless noted;",
    "unknown top-level keys are rejected (strict schema).",
    "",
    "There is **no** `auto_merge` configuration key. The pipeline never merges autonomously.",
    "",
    "## Top-level keys",
    "",
  ];

  const names = Object.keys(props).sort();
  for (const name of names) {
    if (name === "auto_merge") continue;
    lines.push(...renderConfigField(name, props[name]!, 3));
  }

  // Guard: if auto_merge somehow appeared, we already skipped it; also assert in tests.
  return normalizeNewlines(lines.join("\n"));
}

// ---------------------------------------------------------------------------
// CHANGELOG
// ---------------------------------------------------------------------------

export interface ChangelogRelease {
  /** Semver without leading v, e.g. "1.28.4" */
  version: string;
  /** ISO date YYYY-MM-DD when known */
  date?: string;
  /** Tag subject / release body (already plain text) */
  body: string;
}

export interface ChangelogDeps {
  /** Return releases newest-first. Tests inject fixtures; CLI uses git tags. */
  listReleases: () => ChangelogRelease[];
}

/**
 * Pure transform: releases → CHANGELOG.md body (Keep a Changelog-ish).
 */
export function renderChangelogMarkdown(releases: ChangelogRelease[]): string {
  const lines: string[] = [
    "# Changelog",
    "",
    GENERATED_BANNER,
    "",
    "Historical release notes derived from git tags (and optional release bodies).",
    "Forward-looking planning lives in [`ROADMAP.md`](./ROADMAP.md).",
    "",
  ];

  // Newest first
  const sorted = [...releases].sort((a, b) => compareSemverDesc(a.version, b.version));
  for (const rel of sorted) {
    const datePart = rel.date ? ` - ${rel.date}` : "";
    lines.push(`## [${rel.version}]${datePart}`, "");
    const body = (rel.body ?? "").trim();
    if (body) {
      // Prefer the release summary bullets; drop release-PR ceremony that tags
      // often carry verbatim from `pipeline release` PR bodies.
      let cleaned = body
        .replace(/^#+\s*v?[\d.]+\s*[—\-:].*\n+/m, "")
        .replace(/^\*\*Shipped[^*]*\*\*\s*/m, "")
        .replace(/\n*---+\s*\n+[\s\S]*$/m, "") // drop everything after a horizontal rule (merge/token notes)
        .replace(/\n*_Prepared by `pipeline release`_[\s\S]*$/m, "")
        .replace(/\n*\*\*Merging this PR is the final step\.\*\*[\s\S]*$/m, "")
        .trim();
      lines.push(cleaned || "_(no tag body)_", "");
    } else {
      lines.push("_(no tag body)_", "");
    }
  }

  return normalizeNewlines(lines.join("\n"));
}

function compareSemverDesc(a: string, b: string): number {
  const pa = a.replace(/^v/, "").split(".").map((x) => parseInt(x, 10) || 0);
  const pb = b.replace(/^v/, "").split(".").map((x) => parseInt(x, 10) || 0);
  for (let i = 0; i < 3; i++) {
    const d = (pb[i] ?? 0) - (pa[i] ?? 0);
    if (d !== 0) return d;
  }
  return 0;
}

// Re-export helpers used by tests / CLI
export { isDocumentedCommand, listDocumentedCommands, COMMAND_DOCS, COMMAND_REGISTRY };
