// Planning stage: ready → planning → plan-review → implementing → review-1.
//
// Steps:
//   1. Generate the plan via the primary/implementer harness (just text, no code).
//   2. Post the plan as a comment, transition ready → planning.
//   3. Transition planning → plan-review and invoke the secondary/reviewer harness.
//   4. Send reviewer feedback back to the primary harness and require a revised plan.
//   5. Create the worktree.
//   6. Transition plan-review → implementing.
//   7. Run the primary implementer harness in the worktree against the revised impl prompt.
//   8. Verify commits exist, push branch, create PR, transition implementing → review-1.

import {
  addLabel,
  createPr,
  getIssueDetail,
  getPrForIssue,
  postComment,
  setBlocked,
  transition,
} from "../gh.ts";
import { invoke, type HarnessResult } from "../harness.ts";
import {
  branchName,
  createWorktree,
  gitInWorktree,
  hasCommitsAhead,
  slugify,
} from "../worktree.ts";
import {
  buildImplementingPrompt,
  buildPlanningOpenspecPrompt,
  buildPlanningPrompt,
  buildPlanReviewPrompt,
  buildPlanRevisionPrompt,
} from "../prompts/index.ts";
import { runTestGate, testGateBlockReason } from "../testgate.ts";
import * as openspec from "../openspec.ts";
import * as last30days from "../last30days.ts";
import type { Harness, Outcome, PipelineConfig, Stage } from "../types.ts";

export interface AdvanceOpts {
  dryRun?: boolean;
  /** Optional model override forwarded to harnesses that support it. */
  model?: string;
}

export async function advance(
  cfg: PipelineConfig,
  issueNumber: number,
  opts: AdvanceOpts = {},
): Promise<Outcome> {
  if (openspec.shouldPlanWithOpenspec(cfg, cfg.repo_dir)) {
    return advanceOpenspec(cfg, issueNumber, opts);
  }

  const detail = await getIssueDetail(cfg, issueNumber);
  const title = detail.title;
  const body = detail.body;

  const primary: Harness = cfg.harnesses.implementer;
  const reviewer: Harness = cfg.harnesses.reviewer;

  console.log(`[pipeline] #${issueNumber}: planning (impl=${primary}, plan-review=${reviewer})`);

  if (opts.dryRun) {
    console.log(`[pipeline] #${issueNumber}: [dry-run] would plan + ${reviewer} plan-review + ${primary} plan revision + implement + open PR`);
    return { advanced: true, from: "ready", to: "review-1", summary: "[dry-run] planning + plan-review" };
  }

  // ---- Step 0: optional carry-forward context (last30days) ----
  const carryForward = await gatherCarryForward(cfg, issueNumber, title);

  // ---- Step 1: generate plan ----
  const planPrompt = buildPlanningPrompt({ cfg, issueNumber, title, body, carryForward });
  let planResult: HarnessResult;
  try {
    planResult = await invoke(primary, cfg.repo_dir, planPrompt, {
      timeoutSec: cfg.implementation_timeout,
      model: opts.model ?? cfg.models.planning,
    });
  } catch (err) {
    const e = err as Error;
    await setBlocked(cfg, issueNumber, `Plan generation failed: ${e.message}`, "ready");
    return { advanced: false, status: "blocked", reason: `plan failed: ${e.message}` };
  }
  if (!planResult.success || !planResult.stdout.trim()) {
    const reason = planResult.timed_out
      ? `Plan generation timed out after ${planResult.duration.toFixed(0)}s`
      : `Plan generation failed (exit ${planResult.exit_code})`;
    await setBlocked(cfg, issueNumber, reason, "ready");
    return { advanced: false, status: "blocked", reason };
  }
  const plan = planResult.stdout.trim();

  // ---- Step 2: post plan, transition ready → planning ----
  await transition(cfg, issueNumber, "ready", "planning", "Implementation plan generated.");
  await postComment(cfg, issueNumber, `## Implementation Plan\n\n${plan}${footer(cfg)}`);

  // Tag the primary harness early for visibility in transition/blocker comments.
  try {
    await addLabel(cfg, issueNumber, `harness:${primary}`);
  } catch {
    /* idempotent */
  }

  // ---- Steps 3+4: secondary plan review + revision (skippable via steps.plan_review) ----
  let revisedPlan = plan;
  let preImplStage: Stage = "planning";
  if (cfg.steps.plan_review) {
    await transition(
      cfg,
      issueNumber,
      "planning",
      "plan-review",
      `Plan generated by ${primary}. ${reviewer} reviewing before implementation.`,
    );
    preImplStage = "plan-review";

    const reviewPrompt = buildPlanReviewPrompt({ cfg, issueNumber, title, body, plan, reviewer, implementer: primary });
    const reviewResult = await invoke(reviewer, cfg.repo_dir, reviewPrompt, {
      timeoutSec: cfg.review_timeout,
      model: opts.model ?? cfg.models.review,
    });
    if (!reviewResult.success || !reviewResult.stdout.trim()) {
      const reason = reviewResult.timed_out
        ? `Plan review timed out after ${reviewResult.duration.toFixed(0)}s`
        : `Plan review failed (exit ${reviewResult.exit_code})`;
      await setBlocked(cfg, issueNumber, `Plan-review harness (${reviewer}) failed: ${reason}`, "plan-review");
      return { advanced: false, status: "blocked", reason };
    }
    const planReview = reviewResult.stdout.trim();
    await postComment(cfg, issueNumber, `## Plan Review\n\n**Reviewer**: ${reviewer}\n**Implementer**: ${primary}\n\n${planReview}${footer(cfg)}`);

    const revisionPrompt = buildPlanRevisionPrompt({ cfg, issueNumber, title, body, plan, feedback: planReview, reviewer, implementer: primary });
    const revisionResult = await invoke(primary, cfg.repo_dir, revisionPrompt, {
      timeoutSec: cfg.implementation_timeout,
      model: opts.model ?? cfg.models.planning,
    });
    if (!revisionResult.success || !revisionResult.stdout.trim()) {
      const reason = revisionResult.timed_out
        ? `Plan revision timed out after ${revisionResult.duration.toFixed(0)}s`
        : `Plan revision failed (exit ${revisionResult.exit_code})`;
      await setBlocked(cfg, issueNumber, `Plan revision by ${primary} failed: ${reason}`, "plan-review");
      return { advanced: false, status: "blocked", reason };
    }
    revisedPlan = revisionResult.stdout.trim();
    await postComment(cfg, issueNumber, `## Revised Implementation Plan\n\n**Updated by**: ${primary}\n**Based on review by**: ${reviewer}\n\n${revisedPlan}${footer(cfg)}`);
  } else {
    console.log(`[pipeline] #${issueNumber}: plan-review step disabled; implementing the original plan`);
  }

  // ---- Step 5: create worktree ----
  const slug = slugify(title) || `issue-${issueNumber}`;
  let wt: { path: string; branch: string };
  try {
    wt = await createWorktree(cfg, issueNumber, slug);
    console.log(`[pipeline] #${issueNumber}: worktree at ${wt.path}`);
  } catch (err) {
    const e = err as Error;
    await setBlocked(cfg, issueNumber, `Worktree creation failed: ${e.message}`, preImplStage);
    return { advanced: false, status: "blocked", reason: e.message };
  }

  // ---- Step 6: → implementing ----
  await transition(
    cfg,
    issueNumber,
    preImplStage,
    "implementing",
    cfg.steps.plan_review
      ? `Plan reviewed by ${reviewer}, revised by ${primary}. Implementation starting with ${primary}.`
      : `Plan-review step disabled. Implementation starting with ${primary} from the original plan.`,
  );

  // ---- Step 7: primary implementer harness ----
  const implPrompt = buildImplementingPrompt({ cfg, issueNumber, title, body, plan: revisedPlan });
  const result = await invoke(primary, wt.path, implPrompt, {
    timeoutSec: cfg.implementation_timeout,
    model: opts.model,
  });

  if (!result.success) {
    const reason = result.timed_out
      ? `timed out after ${result.duration.toFixed(0)}s`
      : `exit ${result.exit_code}`;
    await setBlocked(
      cfg,
      issueNumber,
      `Implementation harness (${primary}) failed: ${reason}`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason };
  }

  console.log(
    `[pipeline] #${issueNumber}: implementation done (${result.duration.toFixed(0)}s, harness=${primary})`,
  );

  // ---- Step 8: verify commits ----
  const ahead = await hasCommitsAhead(wt.path, cfg.base_branch);
  if (!ahead) {
    await setBlocked(
      cfg,
      issueNumber,
      `Implementation harness (${primary}) completed but produced no commits.`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason: "no commits produced" };
  }

  // ---- Step 8.5: test/build gate (#15) — must pass before opening a PR ----
  const gate = await runTestGate(cfg, issueNumber, wt.path);
  if (!gate.skipped && !gate.passed) {
    await setBlocked(cfg, issueNumber, testGateBlockReason(gate), "implementing");
    return { advanced: false, status: "blocked", reason: "test gate failed" };
  }

  // ---- Step 9: push + PR ----
  const branch = branchName(issueNumber, slug);
  const push = await gitInWorktree(wt.path, ["push", "-u", "origin", branch], {
    ignoreFailure: true,
  });
  if (push.code !== 0) {
    await setBlocked(
      cfg,
      issueNumber,
      `Git push failed: ${push.stderr.trim()}`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason: `push failed` };
  }

  const planExcerpt = revisedPlan.length > 2000 ? revisedPlan.slice(0, 2000) + "\n\n[…plan truncated]" : revisedPlan;
  const prBody = [
    `Closes #${issueNumber}`,
    "",
    `## Summary`,
    `Automated implementation of [${title}](https://github.com/${cfg.repo}/issues/${issueNumber}).`,
    "",
    `**Implemented by**: ${primary}`,
    `**Plan reviewed by**: ${reviewer}`,
    "",
    `## Revised Implementation Plan`,
    planExcerpt,
  ].join("\n") + footer(cfg);

  let prNumber: number;
  try {
    prNumber = await createPr(cfg, {
      branch,
      title: `[Pipeline] ${title} (#${issueNumber})`,
      body: prBody,
    });
  } catch (err) {
    const e = err as Error;
    // Check if a PR already exists (created by a prior partial run).
    const existing = await getPrForIssue(cfg, issueNumber);
    if (existing) {
      prNumber = existing;
    } else {
      await setBlocked(cfg, issueNumber, `PR creation failed: ${e.message}`, "implementing");
      return { advanced: false, status: "blocked", reason: e.message };
    }
  }

  console.log(`[pipeline] #${issueNumber}: PR #${prNumber} created`);

  // ---- Step 10: implementing → review-1 ----
  await transition(
    cfg,
    issueNumber,
    "implementing",
    "review-1",
    `${cfg.implementation_ready_message} PR #${prNumber} created by ${primary}. Plan reviewed by ${reviewer}.`,
  );

  return {
    advanced: true,
    from: "ready",
    to: "review-1",
    summary: `PR #${prNumber} opened after plan-review`,
  };
}

// ---------------------------------------------------------------------------
// OpenSpec planning flow (active when the target repo uses OpenSpec).
//
// Differs from the freeform flow above: the worktree is created FIRST (OpenSpec
// artifacts are files under `openspec/changes/<id>/`), the implementer authors a
// change (proposal/tasks/spec deltas) instead of a freeform plan, the change is
// validated structurally, and its proposal drives the cross-harness plan-review.
// ---------------------------------------------------------------------------

async function advanceOpenspec(
  cfg: PipelineConfig,
  issueNumber: number,
  opts: AdvanceOpts,
): Promise<Outcome> {
  const detail = await getIssueDetail(cfg, issueNumber);
  const { title, body } = detail;
  const primary: Harness = cfg.harnesses.implementer;
  const reviewer: Harness = cfg.harnesses.reviewer;

  console.log(
    `[pipeline] #${issueNumber}: planning (OpenSpec; impl=${primary}, plan-review=${reviewer})`,
  );

  if (opts.dryRun) {
    console.log(
      `[pipeline] #${issueNumber}: [dry-run] would author + ${reviewer} review + revise an OpenSpec change + implement + open PR`,
    );
    return { advanced: true, from: "ready", to: "review-1", summary: "[dry-run] openspec planning" };
  }

  // ---- Step 0: optional carry-forward context (last30days) ----
  const carryForward = await gatherCarryForward(cfg, issueNumber, title);

  // ---- Worktree first: OpenSpec artifacts are files in the change folder. ----
  const slug = slugify(title) || `issue-${issueNumber}`;
  let wt: { path: string; branch: string };
  try {
    wt = await createWorktree(cfg, issueNumber, slug);
    console.log(`[pipeline] #${issueNumber}: worktree at ${wt.path}`);
  } catch (err) {
    const e = err as Error;
    await setBlocked(cfg, issueNumber, `Worktree creation failed: ${e.message}`, "ready");
    return { advanced: false, status: "blocked", reason: e.message };
  }

  // ---- Bootstrap the OpenSpec workspace if the repo lacks one (opt-in). ----
  if (!openspec.isInitialized(wt.path)) {
    if (!cfg.openspec.bootstrap) {
      await setBlocked(
        cfg,
        issueNumber,
        "OpenSpec is required (openspec.enabled: on) but this repo has no `openspec/` " +
          "workspace. Set `openspec.bootstrap: true` in .github/pipeline.yml, or run `openspec init`.",
        "ready",
      );
      return { advanced: false, status: "blocked", reason: "openspec not initialized" };
    }
    console.log(`[pipeline] #${issueNumber}: bootstrapping OpenSpec (openspec init)`);
    const initRes = await openspec.init(wt.path);
    if (initRes.unavailable) {
      await setBlocked(
        cfg,
        issueNumber,
        "OpenSpec bootstrap requested but the `openspec` CLI is not on PATH " +
          "(install: `npm i -g @fission-ai/openspec`).",
        "ready",
      );
      return { advanced: false, status: "blocked", reason: "openspec CLI unavailable" };
    }
    if (!initRes.success) {
      await setBlocked(cfg, issueNumber, `openspec init failed:\n${initRes.output}`, "ready");
      return { advanced: false, status: "blocked", reason: "openspec init failed" };
    }
    await gitInWorktree(wt.path, ["add", "-A"], { ignoreFailure: true });
    await gitInWorktree(
      wt.path,
      ["commit", "-m", `chore: openspec init for #${issueNumber}`],
      { ignoreFailure: true },
    );
  }

  // ---- Author the OpenSpec change (intent only, no code). ----
  const before = openspec.listChangeDirs(wt.path);
  const planResult = await invoke(primary, wt.path, buildPlanningOpenspecPrompt({ cfg, issueNumber, title, body, carryForward }), {
    timeoutSec: cfg.implementation_timeout,
    model: opts.model ?? cfg.models.planning,
  });
  if (!planResult.success) {
    const reason = planResult.timed_out
      ? `timed out after ${planResult.duration.toFixed(0)}s`
      : `exit ${planResult.exit_code}`;
    await setBlocked(cfg, issueNumber, `OpenSpec proposal authoring (${primary}) failed: ${reason}`, "ready");
    return { advanced: false, status: "blocked", reason };
  }

  // ---- Discover the change the implementer created. ----
  const after = openspec.listChangeDirs(wt.path);
  const fresh = after.filter((c) => !before.includes(c));
  const changeId = fresh[0] ?? (after.length === 1 ? after[0] : undefined);
  if (!changeId) {
    await setBlocked(
      cfg,
      issueNumber,
      "OpenSpec is active but the planning step produced no change under `openspec/changes/`. " +
        "Ensure the `openspec` CLI is installed and the repo is initialized (`openspec init`).",
      "ready",
    );
    return { advanced: false, status: "blocked", reason: "no openspec change created" };
  }
  console.log(`[pipeline] #${issueNumber}: OpenSpec change \`${changeId}\` drafted`);

  // ---- Validate the change structurally. ----
  const v1 = await openspec.validateItem(wt.path, changeId);
  if (!v1.unavailable && !v1.valid) {
    await setBlocked(cfg, issueNumber, `OpenSpec change \`${changeId}\` is invalid:\n${formatIssues(v1)}`, "planning");
    return { advanced: false, status: "blocked", reason: "openspec change invalid" };
  }

  const proposal = openspec.readChangeFile(wt.path, changeId, "proposal.md")?.trim() || "(proposal.md not found)";

  // ---- ready → planning, post the proposal as the plan. ----
  await transition(cfg, issueNumber, "ready", "planning", `OpenSpec change \`${changeId}\` drafted by ${primary}.`);
  await postComment(
    cfg,
    issueNumber,
    `## Implementation Plan\n\n_OpenSpec change \`${changeId}\` — proposal.md_\n\n${proposal}${footer(cfg)}`,
  );
  try {
    await addLabel(cfg, issueNumber, `harness:${primary}`);
  } catch {
    /* idempotent */
  }

  // ---- plan review + revision (skippable via steps.plan_review) ----
  let revisedProposal = proposal;
  let preImplStage: Stage = "planning";
  if (cfg.steps.plan_review) {
    await transition(
      cfg,
      issueNumber,
      "planning",
      "plan-review",
      `OpenSpec proposal by ${primary}. ${reviewer} reviewing intent before implementation.`,
    );
    preImplStage = "plan-review";
    const reviewResult = await invoke(
      reviewer,
      wt.path,
      buildPlanReviewPrompt({ cfg, issueNumber, title, body, plan: proposal, reviewer, implementer: primary }),
      { timeoutSec: cfg.review_timeout, model: opts.model ?? cfg.models.review },
    );
    if (!reviewResult.success || !reviewResult.stdout.trim()) {
      const reason = reviewResult.timed_out
        ? `timed out after ${reviewResult.duration.toFixed(0)}s`
        : `exit ${reviewResult.exit_code}`;
      await setBlocked(cfg, issueNumber, `Plan-review harness (${reviewer}) failed: ${reason}`, "plan-review");
      return { advanced: false, status: "blocked", reason };
    }
    const planReview = reviewResult.stdout.trim();
    await postComment(
      cfg,
      issueNumber,
      `## Plan Review\n\n**Reviewer**: ${reviewer}\n**Implementer**: ${primary}\n\n${planReview}${footer(cfg)}`,
    );

    const revisionResult = await invoke(
      primary,
      wt.path,
      buildPlanRevisionPrompt({ cfg, issueNumber, title, body, plan: proposal, feedback: planReview, reviewer, implementer: primary }),
      { timeoutSec: cfg.implementation_timeout, model: opts.model ?? cfg.models.planning },
    );
    if (!revisionResult.success || !revisionResult.stdout.trim()) {
      const reason = revisionResult.timed_out
        ? `timed out after ${revisionResult.duration.toFixed(0)}s`
        : `exit ${revisionResult.exit_code}`;
      await setBlocked(cfg, issueNumber, `Plan revision by ${primary} failed: ${reason}`, "plan-review");
      return { advanced: false, status: "blocked", reason };
    }
    const v2 = await openspec.validateItem(wt.path, changeId);
    if (!v2.unavailable && !v2.valid) {
      await setBlocked(cfg, issueNumber, `OpenSpec change \`${changeId}\` invalid after revision:\n${formatIssues(v2)}`, "plan-review");
      return { advanced: false, status: "blocked", reason: "openspec change invalid after revision" };
    }
    revisedProposal = openspec.readChangeFile(wt.path, changeId, "proposal.md")?.trim() || proposal;
    await postComment(
      cfg,
      issueNumber,
      `## Revised Implementation Plan\n\n**Updated by**: ${primary}\n**Based on review by**: ${reviewer}\n_OpenSpec change \`${changeId}\`_\n\n${revisedProposal}${footer(cfg)}`,
    );
  } else {
    console.log(`[pipeline] #${issueNumber}: plan-review step disabled; implementing the drafted change`);
  }

  // ---- → implementing (work the change's task checklist). ----
  await transition(
    cfg,
    issueNumber,
    preImplStage,
    "implementing",
    cfg.steps.plan_review
      ? `OpenSpec proposal reviewed by ${reviewer}, revised by ${primary}. Implementation starting with ${primary}.`
      : `Plan-review step disabled. Implementation starting with ${primary} from the drafted change.`,
  );
  const tasks = openspec.readChangeFile(wt.path, changeId, "tasks.md")?.trim() ?? "";
  const implPlan =
    `Implement OpenSpec change \`${changeId}\`. Work through the checklist in ` +
    `\`openspec/changes/${changeId}/tasks.md\`, keep that change folder committed, and satisfy its spec deltas.\n\n` +
    `${revisedProposal}${tasks ? `\n\n## Tasks\n\n${tasks}` : ""}`;
  const result = await invoke(
    primary,
    wt.path,
    buildImplementingPrompt({ cfg, issueNumber, title, body, plan: implPlan }),
    { timeoutSec: cfg.implementation_timeout, model: opts.model },
  );
  if (!result.success) {
    const reason = result.timed_out ? `timed out after ${result.duration.toFixed(0)}s` : `exit ${result.exit_code}`;
    await setBlocked(cfg, issueNumber, `Implementation harness (${primary}) failed: ${reason}`, "implementing");
    return { advanced: false, status: "blocked", reason };
  }
  console.log(`[pipeline] #${issueNumber}: implementation done (${result.duration.toFixed(0)}s, harness=${primary})`);

  // ---- Verify commits, push, open PR, implementing → review-1. ----
  if (!(await hasCommitsAhead(wt.path, cfg.base_branch))) {
    await setBlocked(cfg, issueNumber, `Implementation harness (${primary}) completed but produced no commits.`, "implementing");
    return { advanced: false, status: "blocked", reason: "no commits produced" };
  }
  // ---- test/build gate (#15) — must pass before opening a PR ----
  const gate = await runTestGate(cfg, issueNumber, wt.path);
  if (!gate.skipped && !gate.passed) {
    await setBlocked(cfg, issueNumber, testGateBlockReason(gate), "implementing");
    return { advanced: false, status: "blocked", reason: "test gate failed" };
  }
  const branch = branchName(issueNumber, slug);
  const push = await gitInWorktree(wt.path, ["push", "-u", "origin", branch], { ignoreFailure: true });
  if (push.code !== 0) {
    await setBlocked(cfg, issueNumber, `Git push failed: ${push.stderr.trim()}`, "implementing");
    return { advanced: false, status: "blocked", reason: "push failed" };
  }
  const planExcerpt =
    revisedProposal.length > 2000 ? revisedProposal.slice(0, 2000) + "\n\n[…proposal truncated]" : revisedProposal;
  const prBody = [
    `Closes #${issueNumber}`,
    "",
    `## Summary`,
    `Automated implementation of [${title}](https://github.com/${cfg.repo}/issues/${issueNumber}).`,
    "",
    `**Implemented by**: ${primary}`,
    `**Plan reviewed by**: ${reviewer}`,
    `**OpenSpec change**: \`${changeId}\``,
    "",
    `## Proposal`,
    planExcerpt,
  ].join("\n") + footer(cfg);
  let prNumber: number;
  try {
    prNumber = await createPr(cfg, { branch, title: `[Pipeline] ${title} (#${issueNumber})`, body: prBody });
  } catch (err) {
    const existing = await getPrForIssue(cfg, issueNumber);
    if (existing) {
      prNumber = existing;
    } else {
      await setBlocked(cfg, issueNumber, `PR creation failed: ${(err as Error).message}`, "implementing");
      return { advanced: false, status: "blocked", reason: (err as Error).message };
    }
  }
  console.log(`[pipeline] #${issueNumber}: PR #${prNumber} created`);
  await transition(
    cfg,
    issueNumber,
    "implementing",
    "review-1",
    `${cfg.implementation_ready_message} PR #${prNumber} created by ${primary} (OpenSpec change \`${changeId}\`). Plan reviewed by ${reviewer}.`,
  );
  return { advanced: true, from: "ready", to: "review-1", summary: `PR #${prNumber} opened after OpenSpec plan-review` };
}

function formatIssues(v: { issues: { item?: string; message: string }[]; raw: string }): string {
  return v.issues.length
    ? v.issues.map((i) => `- ${i.item ? `${i.item}: ` : ""}${i.message}`).join("\n")
    : v.raw;
}

// ---------------------------------------------------------------------------
// Pre-planning carry-forward context (optional; last30days)
// ---------------------------------------------------------------------------

const LAST30DAYS_SETUP_URL = "https://github.com/mvanhorn/last30days-skill#setup";

/** Returns a non-blocking hint for the two empty-brief cases in gatherCarryForward. Exported for unit tests. */
export function buildSetupHint(issueNumber: number, mode: "unavailable" | "no-signal"): string {
  const p = `[pipeline] #${issueNumber}: last30days:`;
  if (mode === "unavailable") {
    return (
      `${p} skill or Python not found; skipping (non-blocking). ` +
      `To install: \`npx skills add mvanhorn/last30days-skill -g\` (Codex/CLI hosts) or ` +
      `\`/plugin marketplace add mvanhorn/last30days-skill\` (Claude Code). ` +
      `Data-source keys (BRAVE_SEARCH_API_KEY, SCRAPECREATORS_API_KEY) are configured in the skill — see ${LAST30DAYS_SETUP_URL}`
    );
  }
  return (
    `${p} skill ran but returned no usable signal; skipping (non-blocking). ` +
    `Add data-source keys in the skill for better coverage: ` +
    `BRAVE_SEARCH_API_KEY (free Brave Search) and SCRAPECREATORS_API_KEY (fuller social/X). ` +
    `See ${LAST30DAYS_SETUP_URL}`
  );
}

/** Seam for unit-testing the two empty-brief branches without the skill installed. */
export interface CarryForwardDeps {
  run: typeof last30days.run;
}

/**
 * When `last30days.enabled`, run the last30days skill against the issue title and
 * carry the resulting evidence brief forward: post it as an issue comment AND
 * return it for injection into the planning prompt. Always non-blocking — a
 * missing skill, failure, or empty/low-signal brief just returns "".
 */
export async function gatherCarryForward(
  cfg: PipelineConfig,
  issueNumber: number,
  title: string,
  deps: CarryForwardDeps = { run: last30days.run },
): Promise<string> {
  if (!last30days.isEnabled(cfg)) return "";
  console.log(`[pipeline] #${issueNumber}: gathering last30days carry-forward context`);
  const res = await deps.run(title, { timeoutSec: cfg.last30days.timeout });
  if (res.unavailable) {
    console.log(buildSetupHint(issueNumber, "unavailable"));
    return "";
  }
  if (!res.success || !last30days.hasSignal(res.brief)) {
    console.log(buildSetupHint(issueNumber, "no-signal"));
    return "";
  }
  await postComment(
    cfg,
    issueNumber,
    `## Pre-Planning Context — last30days\n\n_Topic: "${title}"_${res.stats ? `\n\n${res.stats}` : ""}\n\n${res.brief}${footer(cfg)}`,
  );
  console.log(`[pipeline] #${issueNumber}: last30days brief posted + carried into planning`);
  return res.brief;
}

function footer(cfg: PipelineConfig): string {
  return `\n\n---\n${cfg.marker_footer}`;
}
