// Planning stage: ready → planning → plan-review → implementing → review-1.
//
// Steps:
//   1. Generate the plan via the primary/implementer harness (just text, no code).
//   2. Post the plan as a comment, transition ready → planning.
//   3. Transition planning → plan-review and invoke the secondary/reviewer harness.
//   4. Send reviewer feedback back to the primary harness and require a revised plan.
//   5. Create the worktree.
//   6. Transition plan-review → implementing.
//   7. Run the primary implementer harness in the worktree against the revised impl prompt.
//   8. Verify commits exist, push branch, create PR, transition implementing → review-1.

import {
  addLabel,
  createPr,
  getIssueDetail,
  getPrForIssue,
  postComment,
  setBlocked,
  transition,
} from "../gh.ts";
import { invoke, type HarnessResult } from "../harness.ts";
import {
  branchName,
  createWorktree,
  gitInWorktree,
  hasCommitsAhead,
  slugify,
} from "../worktree.ts";
import {
  buildImplementingPrompt,
  buildPlanningPrompt,
  buildPlanReviewPrompt,
  buildPlanRevisionPrompt,
} from "../prompts/index.ts";
import type { Harness, Outcome, PipelineConfig } from "../types.ts";

export interface AdvanceOpts {
  dryRun?: boolean;
  /** Optional model override forwarded to harnesses that support it. */
  model?: string;
}

export async function advance(
  cfg: PipelineConfig,
  issueNumber: number,
  opts: AdvanceOpts = {},
): Promise<Outcome> {
  const detail = await getIssueDetail(cfg, issueNumber);
  const title = detail.title;
  const body = detail.body;

  const primary: Harness = cfg.harnesses.implementer;
  const reviewer: Harness = cfg.harnesses.reviewer;

  console.log(`[pipeline] #${issueNumber}: planning (impl=${primary}, plan-review=${reviewer})`);

  if (opts.dryRun) {
    console.log(`[pipeline] #${issueNumber}: [dry-run] would plan + ${reviewer} plan-review + ${primary} plan revision + implement + open PR`);
    return { advanced: true, from: "ready", to: "review-1", summary: "[dry-run] planning + plan-review" };
  }

  // ---- Step 1: generate plan ----
  const planPrompt = buildPlanningPrompt({ cfg, issueNumber, title, body });
  let planResult: HarnessResult;
  try {
    planResult = await invoke(primary, cfg.repo_dir, planPrompt, {
      timeoutSec: cfg.implementation_timeout,
      model: opts.model ?? cfg.models.planning,
    });
  } catch (err) {
    const e = err as Error;
    await setBlocked(cfg, issueNumber, `Plan generation failed: ${e.message}`, "ready");
    return { advanced: false, status: "blocked", reason: `plan failed: ${e.message}` };
  }
  if (!planResult.success || !planResult.stdout.trim()) {
    const reason = planResult.timed_out
      ? `Plan generation timed out after ${planResult.duration.toFixed(0)}s`
      : `Plan generation failed (exit ${planResult.exit_code})`;
    await setBlocked(cfg, issueNumber, reason, "ready");
    return { advanced: false, status: "blocked", reason };
  }
  const plan = planResult.stdout.trim();

  // ---- Step 2: post plan, transition ready → planning ----
  await transition(cfg, issueNumber, "ready", "planning", "Implementation plan generated.");
  await postComment(cfg, issueNumber, `## Implementation Plan\n\n${plan}${footer(cfg)}`);

  // Tag the primary harness early for visibility in transition/blocker comments.
  try {
    await addLabel(cfg, issueNumber, `harness:${primary}`);
  } catch {
    /* idempotent */
  }

  // ---- Step 3: secondary plan review ----
  await transition(
    cfg,
    issueNumber,
    "planning",
    "plan-review",
    `Plan generated by ${primary}. ${reviewer} reviewing before implementation.`,
  );

  const reviewPrompt = buildPlanReviewPrompt({
    cfg,
    issueNumber,
    title,
    body,
    plan,
    reviewer,
    implementer: primary,
  });
  const reviewResult = await invoke(reviewer, cfg.repo_dir, reviewPrompt, {
    timeoutSec: cfg.review_timeout,
    model: opts.model ?? cfg.models.review,
  });

  if (!reviewResult.success || !reviewResult.stdout.trim()) {
    const reason = reviewResult.timed_out
      ? `Plan review timed out after ${reviewResult.duration.toFixed(0)}s`
      : `Plan review failed (exit ${reviewResult.exit_code})`;
    await setBlocked(cfg, issueNumber, `Plan-review harness (${reviewer}) failed: ${reason}`, "plan-review");
    return { advanced: false, status: "blocked", reason };
  }
  const planReview = reviewResult.stdout.trim();
  await postComment(cfg, issueNumber, `## Plan Review\n\n**Reviewer**: ${reviewer}\n**Implementer**: ${primary}\n\n${planReview}${footer(cfg)}`);

  // ---- Step 4: primary revises plan using secondary feedback ----
  const revisionPrompt = buildPlanRevisionPrompt({
    cfg,
    issueNumber,
    title,
    body,
    plan,
    feedback: planReview,
    reviewer,
    implementer: primary,
  });
  const revisionResult = await invoke(primary, cfg.repo_dir, revisionPrompt, {
    timeoutSec: cfg.implementation_timeout,
    model: opts.model ?? cfg.models.planning,
  });

  if (!revisionResult.success || !revisionResult.stdout.trim()) {
    const reason = revisionResult.timed_out
      ? `Plan revision timed out after ${revisionResult.duration.toFixed(0)}s`
      : `Plan revision failed (exit ${revisionResult.exit_code})`;
    await setBlocked(cfg, issueNumber, `Plan revision by ${primary} failed: ${reason}`, "plan-review");
    return { advanced: false, status: "blocked", reason };
  }
  const revisedPlan = revisionResult.stdout.trim();
  await postComment(cfg, issueNumber, `## Revised Implementation Plan\n\n**Updated by**: ${primary}\n**Based on review by**: ${reviewer}\n\n${revisedPlan}${footer(cfg)}`);

  // ---- Step 5: create worktree ----
  const slug = slugify(title) || `issue-${issueNumber}`;
  let wt: { path: string; branch: string };
  try {
    wt = await createWorktree(cfg, issueNumber, slug);
    console.log(`[pipeline] #${issueNumber}: worktree at ${wt.path}`);
  } catch (err) {
    const e = err as Error;
    await setBlocked(cfg, issueNumber, `Worktree creation failed: ${e.message}`, "plan-review");
    return { advanced: false, status: "blocked", reason: e.message };
  }

  // ---- Step 6: plan-review → implementing ----
  await transition(
    cfg,
    issueNumber,
    "plan-review",
    "implementing",
    `Plan reviewed by ${reviewer}, revised by ${primary}. Implementation starting with ${primary}.`,
  );

  // ---- Step 7: primary implementer harness ----
  const implPrompt = buildImplementingPrompt({ cfg, issueNumber, title, body, plan: revisedPlan });
  const result = await invoke(primary, wt.path, implPrompt, {
    timeoutSec: cfg.implementation_timeout,
    model: opts.model,
  });

  if (!result.success) {
    const reason = result.timed_out
      ? `timed out after ${result.duration.toFixed(0)}s`
      : `exit ${result.exit_code}`;
    await setBlocked(
      cfg,
      issueNumber,
      `Implementation harness (${primary}) failed: ${reason}`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason };
  }

  console.log(
    `[pipeline] #${issueNumber}: implementation done (${result.duration.toFixed(0)}s, harness=${primary})`,
  );

  // ---- Step 8: verify commits ----
  const ahead = await hasCommitsAhead(wt.path, cfg.base_branch);
  if (!ahead) {
    await setBlocked(
      cfg,
      issueNumber,
      `Implementation harness (${primary}) completed but produced no commits.`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason: "no commits produced" };
  }

  // ---- Step 9: push + PR ----
  const branch = branchName(issueNumber, slug);
  const push = await gitInWorktree(wt.path, ["push", "-u", "origin", branch], {
    ignoreFailure: true,
  });
  if (push.code !== 0) {
    await setBlocked(
      cfg,
      issueNumber,
      `Git push failed: ${push.stderr.trim()}`,
      "implementing",
    );
    return { advanced: false, status: "blocked", reason: `push failed` };
  }

  const planExcerpt = revisedPlan.length > 2000 ? revisedPlan.slice(0, 2000) + "\n\n[…plan truncated]" : revisedPlan;
  const prBody = [
    `Closes #${issueNumber}`,
    "",
    `## Summary`,
    `Automated implementation of [${title}](https://github.com/${cfg.repo}/issues/${issueNumber}).`,
    "",
    `**Implemented by**: ${primary}`,
    `**Plan reviewed by**: ${reviewer}`,
    "",
    `## Revised Implementation Plan`,
    planExcerpt,
  ].join("\n") + footer(cfg);

  let prNumber: number;
  try {
    prNumber = await createPr(cfg, {
      branch,
      title: `[Pipeline] ${title} (#${issueNumber})`,
      body: prBody,
    });
  } catch (err) {
    const e = err as Error;
    // Check if a PR already exists (created by a prior partial run).
    const existing = await getPrForIssue(cfg, issueNumber);
    if (existing) {
      prNumber = existing;
    } else {
      await setBlocked(cfg, issueNumber, `PR creation failed: ${e.message}`, "implementing");
      return { advanced: false, status: "blocked", reason: e.message };
    }
  }

  console.log(`[pipeline] #${issueNumber}: PR #${prNumber} created`);

  // ---- Step 10: implementing → review-1 ----
  await transition(
    cfg,
    issueNumber,
    "implementing",
    "review-1",
    `${cfg.implementation_ready_message} PR #${prNumber} created by ${primary}. Plan reviewed by ${reviewer}.`,
  );

  return {
    advanced: true,
    from: "ready",
    to: "review-1",
    summary: `PR #${prNumber} opened after plan-review`,
  };
}

function footer(cfg: PipelineConfig): string {
  return `\n\n---\n${cfg.marker_footer}`;
}
