#!/usr/bin/env bash
# Ship playbook: train (--merge) → release → wait GitHub Release → engine-promote.
# Portable example for thin supervisors. Chains existing pipeline CLI only.
#
# This is the chain-to-existing-tools ship: it composes `single`/`train --merge`,
# `release`, `release finish`, and `engine-promote`. It is an ALTERNATIVE to the
# `pipeline ship` coordinator (thin adapter ship-milestone.sh) for hosts that run
# a pipeline build without the `ship` subcommand.
#
#   pipeline-ship-playbook.sh --milestone v1.33.0
#   pipeline-ship-playbook.sh --milestone v1.33.0 --detach
#   pipeline-ship-playbook.sh --milestones v1.33.0 v1.34.0 --detach
#   pipeline-ship-playbook.sh --milestone v1.33.0 --status
#
# Multi-milestone runs are STRICTLY SERIAL: full ship (including engine-promote)
# for each milestone before the next starts.
#
# Do NOT edit this file while a playbook process is running (bash re-reads
# script pages; mid-write can syntax-error a live run).
#
# Environment:
#   REPO_DIR                   Target git checkout (required)
#   PIPELINE                   pipeline launcher (default: pipeline on PATH)
#   ALLOW_MERGE                must be 1 for merge/release finish
#   PIPELINE_SUPERVISOR_STATE  state root (default: ~/.local/state/pipeline-supervisor)
#   SHIP_NOTIFY                1 to post via ship-notify.sh (default 1)
#   SHIP_NOTIFY_BIN            path to ship-notify.sh (default: sibling)
#   SHIP_NOTIFY_HEARTBEAT_S    0 disables phase heartbeats (recommended with stage-watch)
#   SHIP_STAGE_WATCH_BIN       path to ship-stage-watch.sh (default: sibling)
#   ENGINE_PROMOTE_HOST        codex|claude|all (default codex)
#   RELEASE_WAIT_ATTEMPTS      default 30
#   RELEASE_WAIT_SLEEP_S       default 40
#
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PIPELINE="${PIPELINE:-pipeline}"
REPO_DIR="${REPO_DIR:-}"
ALLOW_MERGE="${ALLOW_MERGE:-0}"
STATE_ROOT="${PIPELINE_SUPERVISOR_STATE:-$HOME/.local/state/pipeline-supervisor}"
HOST="${ENGINE_PROMOTE_HOST:-codex}"
RELEASE_WAIT_ATTEMPTS="${RELEASE_WAIT_ATTEMPTS:-30}"
RELEASE_WAIT_SLEEP_S="${RELEASE_WAIT_SLEEP_S:-40}"

SHIP_NOTIFY="${SHIP_NOTIFY:-1}"
SHIP_NOTIFY_BIN="${SHIP_NOTIFY_BIN:-$SCRIPT_DIR/ship-notify.sh}"
# Default 0: stage-watch covers progress; avoid generic "still running" noise
SHIP_NOTIFY_HEARTBEAT_S="${SHIP_NOTIFY_HEARTBEAT_S:-0}"
SHIP_STAGE_WATCH_BIN="${SHIP_STAGE_WATCH_BIN:-$SCRIPT_DIR/ship-stage-watch.sh}"
_HEARTBEAT_PID=""

ship_notify() {
  [[ "${SHIP_NOTIFY}" == "1" ]] || return 0
  [[ -x "$SHIP_NOTIFY_BIN" ]] || return 0
  "$SHIP_NOTIFY_BIN" "$@" || true
}

ship_heartbeat_start() {
  local label=$1
  local key=${2:-heartbeat}
  ship_heartbeat_stop
  [[ "${SHIP_NOTIFY}" == "1" ]] || return 0
  local hb="${SHIP_NOTIFY_HEARTBEAT_S:-0}"
  [[ -n "$hb" && "$hb" != "0" ]] || return 0
  (
    while sleep "${SHIP_NOTIFY_HEARTBEAT_S}"; do
      prog=""
      ev=$(ls -t "${HOME}/.local/state/agent-pipeline/loop/runs/"loop-*/events.jsonl 2>/dev/null | head -1 || true)
      if [[ -n "$ev" ]]; then
        prog=$(python3 -c "import json,sys
stage=issue=None
for line in open(sys.argv[1]):
  line=line.strip()
  if not line: continue
  try: ev=json.loads(line)
  except Exception: continue
  d=ev.get('data') or {}
  if ev.get('kind')=='loop_item_stage_progress':
    stage=d.get('stage'); issue=d.get('item_id')
parts=[]
if issue: parts.append('#'+str(issue))
if stage: parts.append(str(stage))
print(' '.join(parts))" "$ev" 2>/dev/null || true)
      fi
      if [[ -n "$prog" ]]; then
        ship_notify "still running — ${label} (${prog})" "${key}-hb" --force
      else
        ship_notify "still running — ${label}" "${key}-hb" --force
      fi
    done
  ) &
  _HEARTBEAT_PID=$!
}

ship_heartbeat_stop() {
  if [[ -n "${_HEARTBEAT_PID}" ]] && kill -0 "${_HEARTBEAT_PID}" 2>/dev/null; then
    kill "${_HEARTBEAT_PID}" 2>/dev/null || true
    wait "${_HEARTBEAT_PID}" 2>/dev/null || true
  fi
  _HEARTBEAT_PID=""
}

trap_ship_cleanup() {
  ship_heartbeat_stop
  if [[ -n "${lock_dir:-}" ]]; then
    rmdir "$lock_dir" 2>/dev/null || true
  fi
}
trap trap_ship_cleanup EXIT

milestones=()
do_status=0
do_detach=0

usage() {
  cat <<'U'
Usage:
  pipeline-ship-playbook.sh --milestone vX.Y.Z [--detach|--status]
  pipeline-ship-playbook.sh --milestones vA.B.C[,vD.E.F ...] [--detach|--status]

Multi-milestone runs are STRICTLY SERIAL. Each milestone runs the full ship
(train+merge → release → wait → engine-promote) before the next starts.

Required env: REPO_DIR, ALLOW_MERGE=1 (for real ship). Optional: PIPELINE, SHIP_NOTIFY_*.
U
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --milestone|-m)
      [[ -n "${2:-}" ]] || { echo "missing value for $1" >&2; exit 2; }
      milestones+=("$2"); shift 2 ;;
    --milestones)
      shift
      while [[ $# -gt 0 && "$1" != --* ]]; do
        IFS=',' read -r -a parts <<< "$1"
        for p in "${parts[@]}"; do
          p=$(echo "$p" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          [[ -n "$p" ]] && milestones+=("$p")
        done
        shift
      done
      ;;
    --status) do_status=1; shift ;;
    --detach) do_detach=1; shift ;;
    -h|--help) usage; exit 0 ;;
    v[0-9]*|[0-9]*.[0-9]*)
      milestones+=("$1"); shift ;;
    *)
      echo "unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ ${#milestones[@]} -eq 0 ]]; then
  usage
  exit 2
fi

normalize_ms() {
  local m=$1
  if [[ "$m" == v* ]]; then echo "$m"; else echo "v$m"; fi
}

norm=()
for m in "${milestones[@]}"; do
  norm+=("$(normalize_ms "$m")")
done
milestones=("${norm[@]}")

deduped=()
for m in "${milestones[@]}"; do
  skip=0
  for d in "${deduped[@]+"${deduped[@]}"}"; do
    [[ "$d" == "$m" ]] && skip=1 && break
  done
  [[ $skip -eq 0 ]] && deduped+=("$m")
done
milestones=("${deduped[@]}")

version_of() {
  local m=$1
  echo "${m#v}"
}

safe_of() {
  local m=$1
  echo "${m//\//-}"
}

batch_id() {
  local s=""
  local m
  for m in "${milestones[@]}"; do
    s="${s}+$(safe_of "$m")"
  done
  echo "${s#+}"
}

json_str() {
  printf '%s' "$1" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

# ---------- status ----------
if [[ "$do_status" -eq 1 ]]; then
  if [[ ${#milestones[@]} -eq 1 ]]; then
    m=${milestones[0]}
    RUN_DIR="$STATE_ROOT/ship-$(safe_of "$m")"
    STATE_FILE="$RUN_DIR/state.json"
    PID_FILE="$RUN_DIR/playbook.pid"
    if [[ -f "$STATE_FILE" ]]; then
      cat "$STATE_FILE"
      if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "{\"running\": true, \"pid\": $(cat "$PID_FILE")}" >&2
      else
        echo '{"running": false}' >&2
      fi
      exit 0
    fi
    echo "{\"schema_version\":1,\"kind\":\"ship_playbook\",\"status\":\"not_started\",\"milestone\":$(json_str "$m")}"
    exit 0
  fi

  BID=$(batch_id)
  BATCH_DIR="$STATE_ROOT/ship-batch-$BID"
  if [[ -f "$BATCH_DIR/state.json" ]]; then
    cat "$BATCH_DIR/state.json"
    if [[ -f "$BATCH_DIR/batch.pid" ]] && kill -0 "$(cat "$BATCH_DIR/batch.pid")" 2>/dev/null; then
      echo "{\"running\": true, \"pid\": $(cat "$BATCH_DIR/batch.pid")}" >&2
    else
      echo '{"running": false}' >&2
    fi
    echo "--- per-milestone ---" >&2
    for m in "${milestones[@]}"; do
      sf="$STATE_ROOT/ship-$(safe_of "$m")/state.json"
      if [[ -f "$sf" ]]; then
        echo -n "$m: " >&2
        python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("phase"), d.get("status"), d.get("detail","")[:80])' "$sf" >&2 || true
      else
        echo "$m: (no state)" >&2
      fi
    done
    exit 0
  fi
  python3 - <<PY
import json
print(json.dumps({
  "schema_version": 1,
  "kind": "ship_playbook_batch",
  "status": "not_started",
  "milestones": $(python3 -c 'import json; print(json.dumps('"$(
    printf '%s\n' "${milestones[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))'
  )"'))'),
}))
PY
  exit 0
fi

# ---------- detach ----------
if [[ "$do_detach" -eq 1 ]]; then
  if [[ ${#milestones[@]} -eq 1 ]]; then
    m=${milestones[0]}
    RUN_DIR="$STATE_ROOT/ship-$(safe_of "$m")"
    LOG_FILE="$RUN_DIR/playbook.log"
    PID_FILE="$RUN_DIR/playbook.pid"
    mkdir -p "$RUN_DIR"
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
      echo "already running pid=$(cat "$PID_FILE") state=$RUN_DIR/state.json" >&2
      cat "$RUN_DIR/state.json" 2>/dev/null || true
      exit 0
    fi
    : >"$LOG_FILE"
    nohup env PIPELINE="$PIPELINE" REPO_DIR="$REPO_DIR" ALLOW_MERGE="$ALLOW_MERGE" \
      PIPELINE_SUPERVISOR_STATE="$STATE_ROOT" ENGINE_PROMOTE_HOST="$HOST" \
      RELEASE_WAIT_ATTEMPTS="$RELEASE_WAIT_ATTEMPTS" RELEASE_WAIT_SLEEP_S="$RELEASE_WAIT_SLEEP_S" \
      SHIP_NOTIFY="$SHIP_NOTIFY" SHIP_NOTIFY_BIN="$SHIP_NOTIFY_BIN" \
      SHIP_NOTIFY_HEARTBEAT_S="$SHIP_NOTIFY_HEARTBEAT_S" \
      SHIP_STAGE_WATCH_BIN="$SHIP_STAGE_WATCH_BIN" \
      "$0" --milestone "$m" >>"$LOG_FILE" 2>&1 &
    echo $! >"$PID_FILE"
    echo "detached pid=$(cat "$PID_FILE") milestone=$m log=$LOG_FILE"
    ship_notify "detached ship ${m} (pid $(cat "$PID_FILE"))" "detach-$(safe_of "$m")-$$" --force
    exit 0
  fi

  BID=$(batch_id)
  BATCH_DIR="$STATE_ROOT/ship-batch-$BID"
  LOG_FILE="$BATCH_DIR/batch.log"
  PID_FILE="$BATCH_DIR/batch.pid"
  mkdir -p "$BATCH_DIR"
  if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "batch already running pid=$(cat "$PID_FILE") state=$BATCH_DIR/state.json" >&2
    cat "$BATCH_DIR/state.json" 2>/dev/null || true
    exit 0
  fi
  : >"$LOG_FILE"
  args=(--milestones)
  for m in "${milestones[@]}"; do args+=("$m"); done
  nohup env PIPELINE="$PIPELINE" REPO_DIR="$REPO_DIR" ALLOW_MERGE="$ALLOW_MERGE" \
    PIPELINE_SUPERVISOR_STATE="$STATE_ROOT" ENGINE_PROMOTE_HOST="$HOST" \
    RELEASE_WAIT_ATTEMPTS="$RELEASE_WAIT_ATTEMPTS" RELEASE_WAIT_SLEEP_S="$RELEASE_WAIT_SLEEP_S" \
    SHIP_NOTIFY="$SHIP_NOTIFY" SHIP_NOTIFY_BIN="$SHIP_NOTIFY_BIN" \
    SHIP_NOTIFY_HEARTBEAT_S="$SHIP_NOTIFY_HEARTBEAT_S" \
    SHIP_STAGE_WATCH_BIN="$SHIP_STAGE_WATCH_BIN" \
    "$0" "${args[@]}" >>"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"
  cat >"$BATCH_DIR/state.json" <<JSON
{
  "schema_version": 1,
  "kind": "ship_playbook_batch",
  "status": "running",
  "phase": "starting",
  "milestones": $(printf '%s\n' "${milestones[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))'),
  "current_index": 0,
  "current_milestone": $(json_str "${milestones[0]}"),
  "completed": [],
  "failed": null,
  "updated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "log": $(json_str "$LOG_FILE"),
  "pid": $(cat "$PID_FILE")
}
JSON
  echo "detached batch pid=$(cat "$PID_FILE") milestones=${milestones[*]} log=$LOG_FILE state=$BATCH_DIR/state.json"
  ship_notify "detached ship batch: ${milestones[*]} (pid $(cat "$PID_FILE"))" "detach-batch-$(batch_id)"
  exit 0
fi

# ---------- multi foreground ----------
if [[ ${#milestones[@]} -gt 1 ]]; then
  BID=$(batch_id)
  BATCH_DIR="$STATE_ROOT/ship-batch-$BID"
  mkdir -p "$BATCH_DIR"
  echo $$ >"$BATCH_DIR/batch.pid"
  LOG_FILE="$BATCH_DIR/batch.log"
  touch "$LOG_FILE"

  write_batch() {
    local status=$1 phase=$2 idx=$3 cur=$4
    local completed_json=$5
    local failed=${6:-}
    cat >"$BATCH_DIR/state.json" <<JSON
{
  "schema_version": 1,
  "kind": "ship_playbook_batch",
  "status": $(json_str "$status"),
  "phase": $(json_str "$phase"),
  "milestones": $(printf '%s\n' "${milestones[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))'),
  "current_index": $idx,
  "current_milestone": $(json_str "$cur"),
  "completed": $completed_json,
  "failed": $(if [[ -n "$failed" ]]; then json_str "$failed"; else echo null; fi),
  "updated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "log": $(json_str "$LOG_FILE"),
  "pid": $$
}
JSON
    local msg="ship batch: ${phase} → ${status} | current ${cur} ($((idx+1))/${#milestones[@]})"
    [[ -n "$failed" ]] && msg="${msg} | failed: ${failed}"
    ship_notify "$msg" "batch-$(batch_id)-${phase}-${status}-${idx}"
    if [[ "$status" == "running" ]]; then
      ship_heartbeat_start "batch ${cur}" "batch-$(batch_id)"
    else
      ship_heartbeat_stop
    fi
  }

  completed_list=()
  n=${#milestones[@]}
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] batch start: ${milestones[*]}" | tee -a "$LOG_FILE"

  for i in "${!milestones[@]}"; do
    m=${milestones[$i]}
    completed_json=$(printf '%s\n' "${completed_list[@]+"${completed_list[@]}"}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')
    write_batch "running" "shipping" "$i" "$m" "$completed_json" ""
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] === batch item $((i+1))/$n: $m (full ship incl. engine-promote before next) ===" | tee -a "$LOG_FILE"

    set +e
    env PIPELINE="$PIPELINE" REPO_DIR="$REPO_DIR" ALLOW_MERGE="$ALLOW_MERGE" \
      PIPELINE_SUPERVISOR_STATE="$STATE_ROOT" ENGINE_PROMOTE_HOST="$HOST" \
      RELEASE_WAIT_ATTEMPTS="$RELEASE_WAIT_ATTEMPTS" RELEASE_WAIT_SLEEP_S="$RELEASE_WAIT_SLEEP_S" \
      SHIP_NOTIFY="$SHIP_NOTIFY" SHIP_NOTIFY_BIN="$SHIP_NOTIFY_BIN" \
      SHIP_NOTIFY_HEARTBEAT_S="$SHIP_NOTIFY_HEARTBEAT_S" \
      SHIP_STAGE_WATCH_BIN="$SHIP_STAGE_WATCH_BIN" \
      "$0" --milestone "$m" >>"$LOG_FILE" 2>&1
    ec=$?
    set -e

    if [[ $ec -ne 0 ]]; then
      write_batch "failed" "stopped" "$i" "$m" "$completed_json" "$m exit $ec"
      echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] FAIL batch at $m exit=$ec — not starting remaining milestones" | tee -a "$LOG_FILE"
      exit "$ec"
    fi

    sf="$STATE_ROOT/ship-$(safe_of "$m")/state.json"
    if [[ -f "$sf" ]]; then
      st=$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("phase"), d.get("status"))' "$sf" || echo "missing")
      echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $m finished state: $st" | tee -a "$LOG_FILE"
      phase_st=$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("phase","")+"|"+d.get("status",""))' "$sf")
      if [[ "$phase_st" != "complete|ok" ]]; then
        write_batch "failed" "stopped" "$i" "$m" "$completed_json" "$m did not reach complete/ok (got $phase_st); promote may have failed"
        echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] FAIL: refusing next milestone without successful promote" | tee -a "$LOG_FILE"
        exit 1
      fi
    fi

    completed_list+=("$m")
    completed_json=$(printf '%s\n' "${completed_list[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] === $m complete (promoted); starting next if any ===" | tee -a "$LOG_FILE"
  done

  completed_json=$(printf '%s\n' "${completed_list[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')
  write_batch "ok" "complete" "$((n-1))" "${milestones[$((n-1))]}" "$completed_json" ""
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] batch COMPLETE: ${milestones[*]}" | tee -a "$LOG_FILE"
  exit 0
fi

# ---------- single milestone foreground ----------
milestone=${milestones[0]}
version=$(version_of "$milestone")
safe=$(safe_of "$milestone")
RUN_DIR="$STATE_ROOT/ship-$safe"
STATE_FILE="$RUN_DIR/state.json"
LOG_FILE="$RUN_DIR/playbook.log"
PID_FILE="$RUN_DIR/playbook.pid"
lock_dir="$RUN_DIR/lock"

write_state() {
  local phase=$1 status=$2
  local detail=${3:-}
  local now
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  mkdir -p "$RUN_DIR"
  cat > "$STATE_FILE" <<JSON
{
  "schema_version": 1,
  "kind": "ship_playbook",
  "milestone": $(json_str "$milestone"),
  "version": $(json_str "$version"),
  "phase": $(json_str "$phase"),
  "status": $(json_str "$status"),
  "detail": $(json_str "$detail"),
  "updated_at": "$now",
  "log": $(json_str "$LOG_FILE"),
  "pid": ${PID:-$$}
}
JSON
  local msg="ship ${milestone}: ${phase} → ${status}"
  [[ -n "$detail" ]] && msg="${msg} (${detail})"
  ship_notify "$msg" "single-$(safe_of "$milestone")-${phase}-${status}-$$-$(date +%s)" --force
  if [[ "$status" == "running" ]]; then
    ship_heartbeat_start "${milestone} ${phase}" "single-$(safe_of "$milestone")"
  else
    ship_heartbeat_stop
  fi
}

log() {
  local line="[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"
  echo "$line" | tee -a "$LOG_FILE"
}

mkdir -p "$RUN_DIR"
if ! mkdir "$lock_dir" 2>/dev/null; then
  if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    log "another ship playbook holds the lock (pid $(cat "$PID_FILE"))"
    exit 0
  fi
  rmdir "$lock_dir" 2>/dev/null || rm -rf "$lock_dir"
  mkdir "$lock_dir"
fi

echo $$ >"$PID_FILE"
PID=$$
export PID
touch "$LOG_FILE"

if [[ "$ALLOW_MERGE" != "1" ]]; then
  write_state "precheck" "failed" "ALLOW_MERGE is not 1"
  log "FAIL: ALLOW_MERGE=$ALLOW_MERGE (need 1 for ship)"
  exit 2
fi
if [[ -z "$REPO_DIR" || ! -d "$REPO_DIR" ]]; then
  write_state "precheck" "failed" "REPO_DIR missing or not a directory: ${REPO_DIR:-<unset>}"
  log "FAIL: REPO_DIR required"
  exit 2
fi

cd "$REPO_DIR"
log "ship playbook start milestone=$milestone version=$version repo=$REPO_DIR"

# A: train + merge
write_state "train" "running" "pipeline train --milestone $milestone --merge --json"
log "phase train: start"
STAGE_WATCH_PID_FILE="$RUN_DIR/stage-watch.pid"
if [[ -x "$SHIP_STAGE_WATCH_BIN" ]]; then
  # Bind stage-watch to this ship session clock + train.json issue list so
  # historical loop/FRG events are never rebroadcast under this ship label.
  SHIP_SINCE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  nohup env PATH="$(dirname "$SHIP_STAGE_WATCH_BIN"):$PATH" \
    REPO_DIR="$REPO_DIR" SHIP_NOTIFY_BIN="$SHIP_NOTIFY_BIN" \
    PIPELINE_SUPERVISOR_STATE="$STATE_ROOT" \
    "$SHIP_STAGE_WATCH_BIN" \
    --milestone "$milestone" \
    --since "$SHIP_SINCE" \
    --issues-file "$RUN_DIR/train.json" \
    --pid-file "$STAGE_WATCH_PID_FILE" \
    >>"$RUN_DIR/stage-watch.log" 2>&1 &
  log "stage-watch started pid=$! since=$SHIP_SINCE"
fi
set +e
"$PIPELINE" train --milestone "$milestone" --merge --json >"$RUN_DIR/train.json" 2>"$RUN_DIR/train.stderr"
train_ec=$?
set -e
[[ -s "$RUN_DIR/train.stderr" ]] && cat "$RUN_DIR/train.stderr" >>"$LOG_FILE" || true
[[ -s "$RUN_DIR/train.json" ]] && tail -c 4000 "$RUN_DIR/train.json" >>"$LOG_FILE" || true
if [[ "$train_ec" -ne 0 ]]; then
  train_err=$(cat "$RUN_DIR/train.stderr" 2>/dev/null || true)
  if echo "$train_err" | grep -qi 'has no open issues'; then
    log "train: milestone has no open issues — treating as already complete (resume)"
    train_ec=0
    write_state "train" "ok" "no open issues (already shipped)"
  elif python3 - "$RUN_DIR/train.json" <<'PY2'
import json,sys,os
p=sys.argv[1]
if not os.path.exists(p):
  raise SystemExit(1)
raw=open(p).read().strip()
prev=os.path.join(os.path.dirname(p), "train.complete.json")
for path in (prev, p):
  if not os.path.exists(path):
    continue
  try:
    raw=open(path).read().strip()
    dec=json.JSONDecoder(); i=0; objs=[]
    while i < len(raw):
      while i < len(raw) and raw[i].isspace(): i+=1
      if i>=len(raw): break
      try:
        o,j=dec.raw_decode(raw,i); objs.append(o); i=j
      except Exception:
        n=raw.find("{", i+1)
        if n<0: break
        i=n
    for o in reversed(objs):
      if o.get("kind")=="train_status" and o.get("complete") is True:
        raise SystemExit(0)
  except SystemExit:
    raise
  except Exception:
    pass
raise SystemExit(1)
PY2
  then
    log "train: prior train_status complete=true — treating as already complete (resume)"
    train_ec=0
    write_state "train" "ok" "prior complete"
  else
    write_state "train" "failed" "train exit $train_ec"
    log "FAIL: train exit $train_ec"
    if [[ -f "$RUN_DIR/stage-watch.pid" ]]; then
      swp=$(cat "$RUN_DIR/stage-watch.pid" 2>/dev/null || true)
      if [[ -n "$swp" ]] && kill -0 "$swp" 2>/dev/null; then kill "$swp" 2>/dev/null || true; fi
    fi
    exit "$train_ec"
  fi
fi
if [[ -s "$RUN_DIR/train.json" ]]; then
  ok=$(python3 - <<'PY' "$RUN_DIR/train.json"
import json,sys
p=sys.argv[1]
try:
  d=json.load(open(p))
except Exception:
  print("0"); raise SystemExit
if isinstance(d, list):
  d=d[-1]
complete=d.get("complete")
blocker=d.get("blocker")
print("1" if complete and not blocker else "0")
if blocker:
  open(p+".blocker","w").write(str(blocker))
PY
)
  if [[ "$ok" != "1" ]]; then
    detail="train JSON not complete"
    [[ -f "$RUN_DIR/train.json.blocker" ]] && detail=$(cat "$RUN_DIR/train.json.blocker")
    write_state "train" "failed" "$detail"
    log "FAIL: train not complete: $detail"
    exit 1
  fi
fi
log "phase train: ok"
write_state "train" "ok" "complete"

if [[ -f "$RUN_DIR/stage-watch.pid" ]]; then
  swp=$(cat "$RUN_DIR/stage-watch.pid" 2>/dev/null || true)
  if [[ -n "$swp" ]] && kill -0 "$swp" 2>/dev/null; then
    kill "$swp" 2>/dev/null || true
    log "stage-watch stopped pid=$swp"
  fi
fi

# B: release prepare (requires FRG) — auto-generate when evidence is missing
FRG_LATEST="$REPO_DIR/.agent-pipeline/frg/$version/latest.json"
if [[ ! -f "$FRG_LATEST" ]]; then
  write_state "release-prepare" "running" "FRG missing — auto-generating via pipeline-ship-frg $version"
  log "FRG missing at $FRG_LATEST — invoking pipeline-ship-frg $version"
  FRG_BIN="${FRG_BIN:-$SCRIPT_DIR/pipeline-ship-frg}"
  if [[ -x "$FRG_BIN" ]]; then
    ship_notify "ship $milestone: FRG missing — running pipeline-ship-frg $version (auto-generate)" "frg-missing-$version-$$" --force
    set +e
    "$FRG_BIN" "$version" >>"$LOG_FILE" 2>&1
    frg_ec=$?
    set -e
    if [[ $frg_ec -ne 0 || ! -f "$FRG_LATEST" ]]; then
      write_state "release-prepare" "failed" "FRG auto-generate failed (exit $frg_ec) for $version"
      log "FAIL: pipeline-ship-frg $version exit $frg_ec; still missing $FRG_LATEST"
      log "  Check attestation key (PIPELINE_FRG_ATTESTATION_KEY_FILE) and frg.log in $STATE_ROOT/frg-$version/"
      ship_notify "ship $milestone: STOPPED — FRG auto-generate FAILED for $version (exit $frg_ec). See $STATE_ROOT/frg-$version/frg.log" "frg-missing-$version-$$" --force
      exit 2
    fi
  else
    write_state "release-prepare" "failed" "FRG missing for $version and no pipeline-ship-frg at $FRG_BIN"
    log "FAIL: Factory Reliability Gate pass missing at $FRG_LATEST and $FRG_BIN not found"
    log "  See docs/runbooks/frg-pack-checklist.md and docs/factory-reliability-gate-runbook.md"
    ship_notify "ship $milestone: STOPPED — FRG missing for $version (need $FRG_LATEST) and pipeline-ship-frg unavailable." "frg-missing-$version-$$" --force
    exit 2
  fi
  log "FRG auto-generated ok for $version"
fi
write_state "release-prepare" "running" "pipeline release $version --no-edit"
log "phase release-prepare: start"
set +e
"$PIPELINE" release "$version" --no-edit >"$RUN_DIR/release-prepare.out" 2>"$RUN_DIR/release-prepare.err"
rel_ec=$?
set -e
cat "$RUN_DIR/release-prepare.out" >>"$LOG_FILE" 2>/dev/null || true
cat "$RUN_DIR/release-prepare.err" >>"$LOG_FILE" 2>/dev/null || true
if [[ "$rel_ec" -ne 0 ]]; then
  log "release prepare exit $rel_ec — searching existing open PR"
fi

pr=$(python3 - <<'PY' "$RUN_DIR/release-prepare.out" "$RUN_DIR/release-prepare.err" "$version"
import re,sys,subprocess,json
out=open(sys.argv[1]).read()+open(sys.argv[2]).read()
ver=sys.argv[3]
m=re.search(r'/pull/(\d+)', out) or re.search(r'PR\s*#(\d+)', out, re.I) or re.search(r'#(\d{1,6})\b', out)
if m:
  print(m.group(1)); raise SystemExit
try:
  r=subprocess.check_output(["gh","pr","list","--state","open","--json","number,title","--limit","40"], text=True)
  for pr in json.loads(r):
    t=pr.get("title") or ""
    if ver in t and "release" in t.lower():
      print(pr["number"]); raise SystemExit
except Exception:
  pass
print("")
PY
)
if [[ -z "$pr" ]]; then
  rel_err=$(cat "$RUN_DIR/release-prepare.err" 2>/dev/null || true)
  rel_out=$(cat "$RUN_DIR/release-prepare.out" 2>/dev/null || true)
  combined="$rel_err"$'\n'"$rel_out"
  if echo "$combined" | grep -qi 'Factory Reliability Gate pass missing\|frg/.*/latest.json\|factory-gate --for'; then
    write_state "release-prepare" "failed" "FRG missing for $version"
    log "FAIL: FRG pass missing for $version — run factory-gate pack then: pipeline factory-gate --for $version --from-run <pack-run-id>"
    log "  See docs/runbooks/frg-pack-checklist.md"
    ship_notify "ship $milestone: STOPPED — Factory Reliability Gate missing for $version. Issue train may be done; release needs .agent-pipeline/frg/$version/latest.json." "frg-missing-$version-$$" --force
    exit 2
  fi
  write_state "release-prepare" "failed" "could not determine release PR number"
  log "FAIL: no release PR number; release out/err:"
  log "$combined"
  ship_notify "ship $milestone: release-prepare failed (no PR). Check playbook log." "release-prep-fail-$$" --force
  exit 1
fi
log "phase release-prepare: pr=$pr"
write_state "release-prepare" "ok" "pr=$pr"
echo "$pr" >"$RUN_DIR/release.pr"

# C: release finish
write_state "release-finish" "running" "pipeline release finish $pr --json"
log "phase release-finish: start pr=$pr"
set +e
"$PIPELINE" release finish "$pr" --json >"$RUN_DIR/release-finish.json" 2>"$RUN_DIR/release-finish.err"
fin_ec=$?
set -e
cat "$RUN_DIR/release-finish.err" >>"$LOG_FILE" 2>/dev/null || true
cat "$RUN_DIR/release-finish.json" >>"$LOG_FILE" 2>/dev/null || true
if [[ "$fin_ec" -ne 0 ]]; then
  write_state "release-finish" "failed" "exit $fin_ec"
  log "FAIL: release finish exit $fin_ec"
  exit "$fin_ec"
fi
log "phase release-finish: ok"
write_state "release-finish" "ok" "pr=$pr"

# D: wait for GitHub Release
write_state "wait-release" "running" "gh release view v$version"
log "phase wait-release: polling v$version"
published=0
for i in $(seq 1 "$RELEASE_WAIT_ATTEMPTS"); do
  set +e
  gh release view "v$version" --json tagName,isDraft,publishedAt >"$RUN_DIR/gh-release.json" 2>"$RUN_DIR/gh-release.err"
  gec=$?
  set -e
  if [[ "$gec" -eq 0 ]]; then
    draft=$(python3 -c 'import json; d=json.load(open("'"$RUN_DIR/gh-release.json"'")); print("1" if d.get("isDraft") else "0")')
    if [[ "$draft" == "0" ]]; then
      published=1
      log "phase wait-release: published (attempt $i)"
      break
    fi
    log "phase wait-release: draft still (attempt $i)"
  else
    log "phase wait-release: not found yet (attempt $i)"
  fi
  sleep "$RELEASE_WAIT_SLEEP_S"
done
if [[ "$published" -ne 1 ]]; then
  write_state "wait-release" "failed" "Release v$version not published within wait budget"
  log "FAIL: release not published in time"
  exit 1
fi
write_state "wait-release" "ok" "v$version published"

# E: engine-promote
write_state "engine-promote" "running" "pipeline engine-promote --for $version --host $HOST --json"
log "phase engine-promote: start"
set +e
"$PIPELINE" engine-promote --for "$version" --host "$HOST" --json >"$RUN_DIR/engine-promote.json" 2>"$RUN_DIR/engine-promote.err"
pro_ec=$?
set -e
cat "$RUN_DIR/engine-promote.err" >>"$LOG_FILE" 2>/dev/null || true
cat "$RUN_DIR/engine-promote.json" >>"$LOG_FILE" 2>/dev/null || true
if [[ "$pro_ec" -ne 0 ]]; then
  write_state "engine-promote" "failed" "exit $pro_ec"
  log "FAIL: engine-promote exit $pro_ec"
  exit "$pro_ec"
fi
set +e
ver_out=$("$PIPELINE" --version 2>/dev/null)
set -e
log "phase engine-promote: ok installed=$ver_out"
write_state "complete" "ok" "installed=$ver_out"
log "ship playbook COMPLETE milestone=$milestone version=$version"
