// Pure docs generators for CLI reference, config reference, SKILL tables, and
// CHANGELOG (#597). Unit-tested without network/git/subprocess; live I/O is
// injected via deps at the scripts/generate-docs.mjs boundary.

import {
  formatHostUsage,
  listDocumentedCommands,
  type CommandDoc,
  type DocumentedCommand,
} from "./command-docs.ts";
import { COMMAND_REGISTRY } from "./command-registry.ts";
import type { OperationSurfaceEntry } from "./operation-surface.ts";

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

export const CLI_BEGIN_MARKER = "<!-- BEGIN GENERATED: cli-command-table -->";
export const CLI_END_MARKER = "<!-- END GENERATED: cli-command-table -->";

export const GENERATED_BANNER =
  "<!-- Generated by scripts/generate-docs.mjs — do not edit by hand. -->";

/** Normalize trailing newlines for stable comparisons. */
export function normalizeTrailingNewline(text: string): string {
  return text.replace(/\s*$/, "\n");
}

/**
 * Replace the region between stable begin/end markers (exclusive of markers).
 * Throws when markers are missing or mis-ordered.
 */
export function replaceMarkedRegion(
  source: string,
  beginMarker: string,
  endMarker: string,
  body: string,
): string {
  const beginIdx = source.indexOf(beginMarker);
  const endIdx = source.indexOf(endMarker);
  if (beginIdx === -1 || endIdx === -1 || endIdx <= beginIdx) {
    throw new Error(
      `docs-generate: markers not found or mis-ordered (${beginMarker} / ${endMarker})`,
    );
  }
  const before = source.slice(0, beginIdx + beginMarker.length);
  const after = source.slice(endIdx);
  const inner = body.endsWith("\n") ? body : `${body}\n`;
  return `${before}\n${inner}${after}`;
}

// ---------------------------------------------------------------------------
// CLI reference
// ---------------------------------------------------------------------------

export interface RenderCliOptions {
  registry?: Record<string, unknown>;
  docs?: Record<string, CommandDoc>;
  operationSurface?: readonly OperationSurfaceEntry[];
  /** Display token in the intro (e.g. `pipeline` for the CLI binary form). */
  displayToken?: string;
}

/** Emit docs/cli.md from the registry + documentation metadata. */
export function renderCliMarkdown(opts: RenderCliOptions = {}): string {
  const commands = listDocumentedCommands(
    opts.registry ?? COMMAND_REGISTRY,
    opts.docs,
    opts.operationSurface,
  );
  const display = opts.displayToken ?? "pipeline";
  const lines: string[] = [
    "# CLI reference",
    "",
    GENERATED_BANNER,
    "",
    "This page is generated from `COMMAND_REGISTRY`, `OPERATION_SURFACE`, and",
    "co-located metadata in `core/scripts/command-docs.ts`. Do not hand-edit the command inventory.",
    "",
    "Host skills use the same inventory with host-specific invocation tokens:",
    "`/pipeline` (Claude Code) and `$pipeline` (Codex). The Node CLI is `pipeline`.",
    "",
    "Regenerate with `node scripts/generate-docs.mjs` (or `npm run docs:generate`).",
    "",
    "## Commands",
    "",
  ];

  let currentSection = "";
  for (const cmd of commands) {
    if (cmd.section !== currentSection) {
      currentSection = cmd.section;
      const heading = sectionHeading(currentSection);
      lines.push(`### ${heading}`, "");
    }
    const usage = formatHostUsage(display, cmd.usage);
    lines.push(
      `#### \`${cmd.keyword}\``,
      "",
      `- **Usage:** \`${usage}\``,
      `- **Summary:** ${cmd.summary}`,
      "",
    );
  }

  lines.push(
    "## Notes",
    "",
    "- Hidden/undocumented registry keywords (for example agent-only surfaces) are",
    "  omitted here but remain dispatchable when registered.",
    "- Flag allowlists and dispatch semantics live in `command-registry.ts`; this",
    "  page does not redefine them.",
    "",
  );
  return normalizeTrailingNewline(lines.join("\n"));
}

function sectionHeading(section: DocumentedCommand["section"]): string {
  switch (section) {
    case "advance":
      return "Advance & durable runs";
    case "lifecycle":
      return "Lifecycle & release";
    case "factory":
      return "Factory & backlog";
    case "observability":
      return "Observability";
    case "config":
      return "Config & discovery";
    default:
      return "Other";
  }
}

// ---------------------------------------------------------------------------
// Host SKILL command tables
// ---------------------------------------------------------------------------

export interface RenderSkillTableOptions {
  hostToken: string;
  registry?: Record<string, unknown>;
  docs?: Record<string, CommandDoc>;
  operationSurface?: readonly OperationSurfaceEntry[];
}

/**
 * Emit the body of a SKILL command-table region (no markers).
 * Hosts differ only by invocation token.
 */
export function renderSkillCommandTable(opts: RenderSkillTableOptions): string {
  const commands = listDocumentedCommands(
    opts.registry ?? COMMAND_REGISTRY,
    opts.docs,
    opts.operationSurface,
  );
  const token = opts.hostToken.trim();
  const pad = 48;
  const lines: string[] = [
    "```",
    `${padRight(`${token} N`, pad)}durable autonomous one-item drive (default)`,
  ];
  for (const cmd of commands) {
    if (cmd.keyword === "advance") continue; // covered by the default N line
    const usage = formatHostUsage(token, cmd.usage);
    lines.push(`${padRight(usage, pad)}${cmd.summary}`);
  }
  lines.push("```", "");
  return lines.join("\n");
}

function padRight(s: string, width: number): string {
  if (s.length >= width) return `${s} `;
  return s + " ".repeat(width - s.length);
}

/** Rewrite a host SKILL file's generated command-table region. */
export function applySkillCommandTable(
  skillSource: string,
  hostToken: string,
  opts: Omit<RenderSkillTableOptions, "hostToken"> = {},
): string {
  const body = renderSkillCommandTable({ ...opts, hostToken });
  return replaceMarkedRegion(skillSource, CLI_BEGIN_MARKER, CLI_END_MARKER, body);
}

// ---------------------------------------------------------------------------
// Config reference
// ---------------------------------------------------------------------------

export type JsonSchemaNode = {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  properties?: Record<string, JsonSchemaNode>;
  items?: JsonSchemaNode;
  anyOf?: JsonSchemaNode[];
  oneOf?: JsonSchemaNode[];
  $ref?: string;
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  minLength?: number;
  additionalProperties?: boolean | JsonSchemaNode;
  [key: string]: unknown;
};

export interface RenderConfigOptions {
  schema: JsonSchemaNode;
  /** Optional defaults map (e.g. DEFAULT_CONFIG); dotted paths not required. */
  defaults?: Record<string, unknown>;
}

/**
 * Emit docs/config.md from a JSON Schema object derived from PartialConfigSchema.
 * Omits keys the schema does not list (e.g. auto_merge is never a property).
 */
export function renderConfigMarkdown(opts: RenderConfigOptions): string {
  const props = opts.schema.properties ?? {};
  const lines: string[] = [
    "# Config reference",
    "",
    GENERATED_BANNER,
    "",
    "Generated from the Zod `PartialConfigSchema` surface in `core/scripts/config.ts`",
    "(via `generateConfigSchema()` / `pipeline config schema`). Commit",
    "`.github/pipeline.yml` to override defaults. Keys rejected by the schema",
    "(for example `auto_merge`) are **not** documented here.",
    "Merge authority is not repository configuration and cannot be set here.",
    "",
    "Regenerate with `node scripts/generate-docs.mjs` (or `npm run docs:generate`).",
    "",
    "## Top-level keys",
    "",
  ];

  const keys = Object.keys(props).sort((a, b) => a.localeCompare(b));
  for (const key of keys) {
    const node = props[key]!;
    lines.push(...renderConfigKey(key, node, opts.defaults?.[key], 0));
  }

  lines.push(
    "## Notes",
    "",
    "- Descriptions come from Zod `.describe()` annotations on the schema.",
    "- Nested objects expand one level of children when present.",
    "- For machine-readable validation, use `pipeline config schema` and",
    "  `pipeline config validate`.",
    "",
  );
  return normalizeTrailingNewline(lines.join("\n"));
}

function renderConfigKey(
  name: string,
  node: JsonSchemaNode,
  defaultValue: unknown,
  depth: number,
): string[] {
  const indent = "";
  const headingLevel = depth === 0 ? "###" : "####";
  const typeStr = describeType(node);
  const desc = (node.description ?? "").trim() || "(no description)";
  const lines: string[] = [
    `${headingLevel} \`${name}\``,
    "",
    `- **Type:** ${typeStr}`,
  ];
  if (defaultValue !== undefined) {
    lines.push(`- **Default:** \`${formatDefault(defaultValue)}\``);
  }
  lines.push(`- **Description:** ${desc}`, "");

  if (node.enum && node.enum.length > 0) {
    lines.push(`- **Allowed values:** ${node.enum.map((v) => `\`${String(v)}\``).join(", ")}`, "");
  }

  const childProps = node.properties;
  if (childProps && depth < 1) {
    const childKeys = Object.keys(childProps).sort((a, b) => a.localeCompare(b));
    if (childKeys.length > 0) {
      lines.push("Nested fields:", "");
      for (const ck of childKeys) {
        lines.push(...renderConfigKey(`${name}.${ck}`, childProps[ck]!, undefined, depth + 1));
      }
    }
  }
  return lines;
}

function describeType(node: JsonSchemaNode): string {
  if (node.enum) return `enum`;
  if (node.type) {
    if (Array.isArray(node.type)) return node.type.join(" | ");
    if (node.type === "array" && node.items) {
      return `array of ${describeType(node.items)}`;
    }
    if (node.type === "object" && node.properties) return "object";
    return String(node.type);
  }
  if (node.anyOf) return node.anyOf.map(describeType).join(" | ");
  if (node.oneOf) return node.oneOf.map(describeType).join(" | ");
  return "unknown";
}

function formatDefault(value: unknown): string {
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

// ---------------------------------------------------------------------------
// CHANGELOG
// ---------------------------------------------------------------------------

export interface ChangelogRelease {
  /** Semver without leading v, e.g. "1.29.1". */
  version: string;
  /** ISO date YYYY-MM-DD when known. */
  date?: string;
  /** Tag subject / release title body. */
  subject?: string;
  /** Optional longer release body (GitHub Release notes). */
  body?: string;
}

export interface ChangelogDeps {
  /** List releases newest-first or any order; generator sorts. */
  listReleases: () => ChangelogRelease[] | Promise<ChangelogRelease[]>;
}

/**
 * Pure transform: releases → CHANGELOG.md (Keep a Changelog-ish headings).
 */
export function renderChangelogMarkdown(releases: ChangelogRelease[]): string {
  const sorted = [...releases].sort((a, b) => compareSemverDesc(a.version, b.version));
  const lines: string[] = [
    "# Changelog",
    "",
    GENERATED_BANNER,
    "",
    "Release history generated from git tags (and optional GitHub Release bodies).",
    "GitHub milestones own planned release membership; [ROADMAP.md](ROADMAP.md) is human-readable forward documentation.",
    "",
    "Regenerate with `node scripts/generate-docs.mjs` (or `npm run docs:generate`).",
    "",
  ];

  for (const rel of sorted) {
    const ver = rel.version.replace(/^v/, "");
    const datePart = rel.date ? ` - ${rel.date}` : "";
    lines.push(`## [${ver}]${datePart}`, "");
    const subject = (rel.subject ?? "").trim();
    const body = (rel.body ?? "").trim();
    if (subject) {
      // Avoid duplicating "vX.Y.Z —" prefixes when the tag subject already has them.
      const cleaned = subject
        .replace(new RegExp(`^v?${escapeRegExp(ver)}\\s*[—–-]\\s*`), "")
        .replace(/^release:\\s*/i, "")
        .trim();
      if (cleaned) lines.push(cleaned, "");
    }
    if (body && body !== subject) {
      lines.push(body, "");
    }
    if (!subject && !body) {
      lines.push(`Tag \`v${ver}\`.`, "");
    }
  }

  if (sorted.length === 0) {
    lines.push("_No version tags found._", "");
  }

  return normalizeTrailingNewline(lines.join("\n"));
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Compare semver strings descending (newest first). Non-numeric tails sort last. */
export function compareSemverDesc(a: string, b: string): number {
  const pa = parseSemver(a);
  const pb = parseSemver(b);
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pb[i] - pa[i];
  }
  return 0;
}

function parseSemver(v: string): [number, number, number] {
  const m = v.replace(/^v/, "").match(/^(\d+)\.(\d+)\.(\d+)/);
  if (!m) return [0, 0, 0];
  return [Number(m[1]), Number(m[2]), Number(m[3])];
}

/**
 * Default git-tag reader for CHANGELOG generation. Injectable for tests via deps.
 * Parses `git tag -l --format=...` output lines: `tag|date|subject`.
 */
export function parseGitTagListLines(stdout: string): ChangelogRelease[] {
  const releases: ChangelogRelease[] = [];
  for (const line of stdout.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const [tag, date, ...rest] = line.split("|");
    if (!tag) continue;
    const m = tag.trim().match(/^v(\d+\.\d+\.\d+)$/);
    if (!m) continue;
    releases.push({
      version: m[1]!,
      date: date?.trim() || undefined,
      subject: rest.join("|").trim() || undefined,
    });
  }
  return releases;
}

// ---------------------------------------------------------------------------
// Artifact set (for generate-docs.mjs)
// ---------------------------------------------------------------------------

export type GeneratedArtifact = {
  /** Path relative to repo root. */
  relPath: string;
  /** Full file contents after generation. */
  content: string;
};

export interface BuildArtifactsInput {
  skillClaude?: string;
  skillCodex?: string;
  skillOmp?: string;
  skillOpencode?: string;
  configSchema: JsonSchemaNode;
  configDefaults?: Record<string, unknown>;
  changelogReleases: ChangelogRelease[];
  registry?: Record<string, unknown>;
  docs?: Record<string, CommandDoc>;
  operationSurface?: readonly OperationSurfaceEntry[];
}

/**
 * Build the full set of generator-owned artifacts (pure).
 * SKILL paths are only included when source text is provided.
 */
export function buildGeneratedArtifacts(input: BuildArtifactsInput): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [
    {
      relPath: "docs/cli.md",
      content: renderCliMarkdown({
        registry: input.registry,
        docs: input.docs,
        operationSurface: input.operationSurface,
      }),
    },
    {
      relPath: "docs/config.md",
      content: renderConfigMarkdown({
        schema: input.configSchema,
        defaults: input.configDefaults,
      }),
    },
    {
      relPath: "CHANGELOG.md",
      content: renderChangelogMarkdown(input.changelogReleases),
    },
  ];

  const hostSkills = [
    { relPath: "hosts/claude/SKILL.md", source: input.skillClaude, token: "/pipeline" },
    { relPath: "hosts/codex/SKILL.md", source: input.skillCodex, token: "$pipeline" },
    { relPath: "hosts/omp/SKILL.md", source: input.skillOmp, token: "/pipeline" },
    { relPath: "hosts/opencode/SKILL.md", source: input.skillOpencode, token: "/pipeline" },
  ];
  for (const host of hostSkills) {
    if (host.source === undefined) continue;
    artifacts.push({
      relPath: host.relPath,
      content: normalizeTrailingNewline(
        applySkillCommandTable(host.source, host.token, {
          registry: input.registry,
          docs: input.docs,
          operationSurface: input.operationSurface,
        }),
      ),
    });
  }

  return artifacts;
}
